### ISSUE TITLE
Stopped because outside valid range

### ISSUE THREAD

**Issue by kimme1024** [flashg1/TeslaSolarCharger#4]
Here we are again :)

The automation was running perfectly, however one way or the other the car decided to lower it's maximum amps from 13 to 12. No idea why he did it (I'm new to Tesla).
Anyway, this caused the automation to stop as it was outside the valid range (13 in settings).
Could this be implemented that when the car's maximum range changes, the automation adapts instead of stopping?

```
Stopped because an error was encountered at 14 september 2023 om 13:58:21 (runtime: 3502.08 seconds)

Value 13.0 for number.wattson_charging_amps is outside valid range 0 - 12
```

**Comment by flashg1** [comment]
Please provide screenshot of trace to show where this is failing.  Please also provide log messages and values.  Thanks.

**Comment by kimme1024** [comment]
> Please provide screenshot of trace to show where this is failing. Please also provide log messages and values. Thanks.

Problem is that there's only that error message.
I've been looking around and can't find anything else that refers to that error.
Somehow the car decided that it wanted to max out at 12A instead of 13A.

I think the only way to solve this is to check if the car's maximum has changed and adapt to that.
For now I've set the limit in the automation to 12 and it has been running fine since then. However it would be nice to know it could max out of possible.
I also don't have any idea why the car would have changed it's maximum amps...

Below is some info. If you'd need more I can still provide it until the automation starts running again tomorrow as it's the first log that will be overwritten.

Trace Timeline:

```
Triggered manually at 14 september 2023 om 12:59:59

Service "Knop: Druk" aanroepen op "Wattson Wake up"

(button.wattson_wake_up) turned 2023-09-14T10:59:59.617252+00:00

Vertraging gebaseerd op een sjabloon
40 seconden later

Service "Knop: Druk" aanroepen op "Wattson Force data update"

(button.wattson_force_data_update) turned 2023-09-14T11:00:39.900301+00:00

Vertraging gebaseerd op een sjabloon
5 seconden later

Service "Scène: Aanmaken" aanroepen op ""

Vertraging gebaseerd op een sjabloon
5 seconden later

Actie terwijl 1 voorwaarde overeenkomt herhalen

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:00:50.218144+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:01:25.645057+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:02:02.111758+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:02:37.598163+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:03:14.094426+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:03:49.529231+00:00
37 seconden later

unknown

(number.wattson_charging_amps) turned 12
(number.wattson_charging_amps) turned 11
Show 7 more items
36 seconden later

unknown

(number.wattson_charging_amps) turned 4
(button.wattson_force_data_update) turned 2023-09-14T11:05:07.190735+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:05:43.097024+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:06:18.501666+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:06:53.957629+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:07:29.470241+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 3
(button.wattson_force_data_update) turned 2023-09-14T11:08:06.050356+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:08:41.444726+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 4
(button.wattson_force_data_update) turned 2023-09-14T11:09:18.006867+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:09:54.130427+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:10:30.015000+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 5
(button.wattson_force_data_update) turned 2023-09-14T11:11:06.735560+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:11:42.062323+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:12:17.557189+00:00
37 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:12:54.169334+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:13:29.975368+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:14:06.169018+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:14:41.695254+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:15:17.214554+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 4
(button.wattson_force_data_update) turned 2023-09-14T11:15:54.151084+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:16:29.656351+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:17:06.148996+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 3
(button.wattson_force_data_update) turned 2023-09-14T11:17:42.514878+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:18:17.859129+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:18:54.176919+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:19:29.718868+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 4
(button.wattson_force_data_update) turned 2023-09-14T11:20:06.957838+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:20:42.302163+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 5
(button.wattson_force_data_update) turned 2023-09-14T11:21:18.534251+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:21:54.434231+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:22:29.863869+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:23:06.173055+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:23:41.700670+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:24:17.136349+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 6
(button.wattson_force_data_update) turned 2023-09-14T11:24:53.823905+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:25:29.140698+00:00
37 seconden later

unknown

(number.wattson_charging_amps) turned 7
(button.wattson_force_data_update) turned 2023-09-14T11:26:06.836888+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:26:42.135198+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:27:17.580204+00:00
37 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:27:54.179432+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 6
(number.wattson_charging_amps) turned 5
(button.wattson_force_data_update) turned 2023-09-14T11:28:30.672033+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 4
(button.wattson_force_data_update) turned 2023-09-14T11:29:07.334565+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:29:42.645654+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:30:18.213370+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:30:54.204022+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:31:29.623795+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 6
(button.wattson_force_data_update) turned 2023-09-14T11:32:06.174738+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:32:41.457047+00:00
37 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:33:18.160909+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:33:53.602335+00:00
37 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:34:30.187937+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 5
(number.wattson_charging_amps) turned 4
Show 3 more items
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:35:44.356297+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 3
(number.wattson_charging_amps) turned 4
Show 5 more items
36 seconden later

unknown

(number.wattson_charging_amps) turned 9
(number.wattson_charging_amps) turned 10
Show 2 more items
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:37:36.462149+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 12
(button.wattson_force_data_update) turned 2023-09-14T11:38:12.997224+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:38:48.356866+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:39:24.455021+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:39:59.898484+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 11
(button.wattson_force_data_update) turned 2023-09-14T11:40:37.261040+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:41:12.545334+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 10
(number.wattson_charging_amps) turned 9
(button.wattson_force_data_update) turned 2023-09-14T11:41:49.306028+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:42:25.227284+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 8
(number.wattson_charging_amps) turned 7
(button.wattson_force_data_update) turned 2023-09-14T11:43:01.710208+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:43:37.564483+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:44:13.039632+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:44:49.223606+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 6
(button.wattson_force_data_update) turned 2023-09-14T11:45:25.915660+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 7
(button.wattson_force_data_update) turned 2023-09-14T11:46:02.861813+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 8
(number.wattson_charging_amps) turned 9
(button.wattson_force_data_update) turned 2023-09-14T11:46:39.191626+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:47:15.245669+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 10
(button.wattson_force_data_update) turned 2023-09-14T11:47:51.693164+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:48:27.577911+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 11
(button.wattson_force_data_update) turned 2023-09-14T11:49:03.796312+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 12
(button.wattson_force_data_update) turned 2023-09-14T11:49:39.847092+00:00
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:50:15.224836+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 11
(button.wattson_force_data_update) turned 2023-09-14T11:50:51.462879+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 10
(button.wattson_force_data_update) turned 2023-09-14T11:51:27.879774+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 9
(number.wattson_charging_amps) turned 8
Show 6 more items
36 seconden later

unknown

(number.wattson_charging_amps) turned 2
(number.wattson_charging_amps) turned 1
Show 2 more items
35 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:53:20.697075+00:00
37 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:53:57.264452+00:00
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:54:32.843060+00:00
38 seconden later

unknown

(number.wattson_charging_amps) turned 1
(number.wattson_charging_amps) turned 2
Show 2 more items
35 seconden later

unknown

(number.wattson_charging_amps) turned 2
(number.wattson_charging_amps) turned 1
Show 2 more items
36 seconden later

unknown

(button.wattson_force_data_update) turned 2023-09-14T11:56:27.465415+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 1
(number.wattson_charging_amps) turned 2
(button.wattson_force_data_update) turned 2023-09-14T11:57:04.346377+00:00
36 seconden later

unknown

(number.wattson_charging_amps) turned 3
(number.wattson_charging_amps) turned 4
(number.wattson_charging_amps) turned 5
1 seconde later

(number.wattson_charging_amps) turned 6
(button.wattson_force_data_update) turned 2023-09-14T11:57:43.354454+00:00
35 seconden later

unknown

(number.wattson_charging_amps) turned 7
(number.wattson_charging_amps) turned 8
(number.wattson_charging_amps) turned 9
(number.wattson_charging_amps) turned 10
(number.wattson_charging_amps) turned 11
(number.wattson_charging_amps) turned 12

Stopped because an error was encountered at 14 september 2023 om 13:58:21 (runtime: 3502.08 seconds)

Value 13.0 for number.wattson_charging_amps is outside valid range 0 - 12
```

Screenshot:
![Scherm­afbeelding 2023-09-14 om 22 58 57](https://github.com/flashg1/TeslaSolarCharger/assets/42653485/0bc882cd-1c96-470c-9689-dd9c5aed79cf)


Automation Config:

```
variables:
  initial_charge_current: 6
  wait_car_wakeup: 40
  wait_charger_on: 11
  wait_charger_off: 5
  wait_current_change: 0.3
  wait_command_execute: 5
  skew_default: -0.3
  charge_from_grid: input_boolean.tesla_model_s_charge_from_grid
  stop_charger: input_boolean.tesla_model_s_stop_charging
  car_charger_voltage: 230
  car_charger_max_current: 13
  one_amp_watt_step: '{{ car_charger_voltage * 1 }}'
  car_chargelimit_ent: number.wattson_charge_limit
  car_chargelimit_last: '{{ expand(car_chargelimit_ent)[0].last_changed | as_timestamp }}'
  car_chargelimit_val: '{{ expand(car_chargelimit_ent)[0].state }}'
  car_batterylevel_ent: sensor.wattson_battery
  car_batterylevel_last: '{{ expand(car_batterylevel_ent)[0].last_changed | as_timestamp }}'
  car_batterylevel_val: '{{ expand(car_batterylevel_ent)[0].state }}'
  car_charging_amps: number.wattson_charging_amps
trigger:
  - platform: state
    entity_id:
      - binary_sensor.wattson_charger
    to: 'on'
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
condition:
  - condition: state
    entity_id: device_tracker.wattson_location_tracker
    state: home
  - condition: state
    entity_id: binary_sensor.wattson_charger
    state: 'on'
action:
  - service: button.press
    data: {}
    target:
      entity_id: button.wattson_wake_up
  - delay: '{{ wait_car_wakeup }}'
  - service: button.press
    data: {}
    target:
      entity_id: button.wattson_force_data_update
  - delay: '{{ wait_command_execute }}'
  - service: scene.create
    data:
      scene_id: tesla_solar_charger_script_scene
      snapshot_entities:
        - number.wattson_charge_limit
        - number.wattson_charging_amps
  - delay: '{{ wait_command_execute }}'
  - repeat:
      while:
        - condition: and
          conditions:
            - condition: template
              value_template: '{{ is_state(stop_charger, ''off'') }}'
            - condition: state
              entity_id: binary_sensor.wattson_charger
              state: 'on'
            - condition: template
              value_template: >-
                {{ (expand(car_batterylevel_ent)[0].state | int) <
                (expand(car_chargelimit_ent)[0].state | int) }}
            - condition: or
              conditions:
                - condition: template
                  value_template: '{{ is_state(charge_from_grid, ''on'') }}'
                - condition: sun
                  after: sunrise
                  before: sunset
                  before_offset: '-00:30:00'
      sequence:
        - variables:
            grid_power_net: sensor.grid_power_net
            homebattery_power_net: sensor.wattson_shift_state
            homebattery_level: sensor.wattson_shift_state
            skew: |-
              {% if skew_default <= -1 %}
                {{ skew_default }}
              {% elif states(homebattery_level) | float(90) < 90 %}
                {{ -1.01 }}  
              {% else %}
                {{ skew_default }} 
              {% endif %}
```
